const initialdata = {
  players: {
    p01: { id: "p01", wins: 0, losses: 4, pdiff: -24, seed: 0, name: "Nate" },
    p02: {
      id: "p02",
      wins: 1,
      losses: 3,
      pdiff: -9,
      seed: 0,
      name: "Mike Becker",
    },
    p03: { id: "p03", wins: 0, losses: 4, pdiff: -24, seed: 0, name: "Jim D" },
    p04: { id: "p04", wins: 3, losses: 1, pdiff: 17, seed: 0, name: "Trem" },
    p05: {
      id: "p05",
      wins: 0,
      losses: 4,
      pdiff: -20,
      seed: 0,
      name: "Chris D",
    },
    p06: { id: "p06", wins: 2, losses: 2, pdiff: 1, seed: 0, name: "Tony L" },
    p07: {
      id: "p07",
      wins: 2,
      losses: 3,
      pdiff: 11,
      seed: 0,
      name: "David Gagliano",
    },
    p08: { id: "p08", wins: 3, losses: 1, pdiff: 12, seed: 0, name: "Mike B" },
    p09: { id: "p09", wins: 3, losses: 2, pdiff: 21, seed: 0, name: "Tom S" },
    p10: { id: "p10", wins: 2, losses: 2, pdiff: -2, seed: 0, name: "Mickey" },
    p11: { id: "p11", wins: 4, losses: 0, pdiff: 28, seed: 0, name: "Joe S" },
    p12: { id: "p12", wins: 2, losses: 2, pdiff: 6, seed: 0, name: "Diaferio" },
    p13: { id: "p13", wins: 2, losses: 2, pdiff: 1, seed: 0, name: "Jeff M" },
    p14: {
      id: "p14",
      wins: 4,
      losses: 0,
      pdiff: 17,
      seed: 0,
      name: "Seteve D",
    },
    p15: { id: "p15", wins: 1, losses: 3, pdiff: -6, seed: 0, name: "John V" },
    p16: { id: "p16", wins: 0, losses: 4, pdiff: -19, seed: 0, name: "Felipe" },
    p17: { id: "p17", wins: 4, losses: 0, pdiff: 24, seed: 0, name: "Mav" },
    p18: { id: "p18", wins: 3, losses: 1, pdiff: 16, seed: 0, name: "Darcy" },
    p19: { id: "p19", wins: 1, losses: 3, pdiff: -17, seed: 0, name: "Olson" },
    p20: { id: "p20", wins: 3, losses: 1, pdiff: 2, seed: 0, name: "Kenny B" },
    p21: { id: "p21", wins: 3, losses: 1, pdiff: 19, seed: 0, name: "Z" },
    p22: {
      id: "p22",
      wins: 2,
      losses: 2,
      pdiff: 5,
      seed: 0,
      name: "Will Babel",
    },
    p23: { id: "p23", wins: 2, losses: 2, pdiff: 12, seed: 0, name: "Patrick" },
    p24: { id: "p24", wins: 1, losses: 3, pdiff: -17, seed: 0, name: "Jeff U" },
    p25: { id: "p25", wins: 1, losses: 3, pdiff: -2, seed: 0, name: "Skiba" },
    p26: { id: "p26", wins: 2, losses: 2, pdiff: -13, seed: 0, name: "Ben" },
    p27: {
      id: "p27",
      wins: 3,
      losses: 1,
      pdiff: 9,
      seed: 0,
      name: "Dave Thompson",
    },
    p28: { id: "p28", wins: 2, losses: 2, pdiff: 7, seed: 0, name: "Brad" },
    p29: {
      id: "p29",
      wins: 0,
      losses: 4,
      pdiff: -38,
      seed: 0,
      name: "Adam Hofferica",
    },
    p30: {
      id: "p30",
      wins: 4,
      losses: 0,
      pdiff: 23,
      seed: 0,
      name: "George Brown",
    },
    p31: {
      id: "p31",
      wins: 3,
      losses: 1,
      pdiff: 7,
      seed: 0,
      name: "Mike McPherson",
    },
    p32: {
      id: "p32",
      wins: 3,
      losses: 1,
      pdiff: 16,
      seed: 0,
      name: "Phil Ross",
    },
    p33: {
      id: "p33",
      wins: 2,
      losses: 2,
      pdiff: 7,
      seed: 0,
      name: "Rich Driscoll",
    },
    p34: { id: "p34", wins: 0, losses: 4, pdiff: 28, seed: 0, name: "Parikh" },
    p35: {
      id: "p35",
      wins: 2,
      losses: 2,
      pdiff: -6,
      seed: 0,
      name: "Pete Jahn",
    },
    p36: { id: "p36", wins: 3, losses: 1, pdiff: 24, seed: 0, name: "Slava" },
    p37: { id: "p37", wins: 0, losses: 4, pdiff: -25, seed: 0, name: "Oneil" },
    p38: { id: "p38", wins: 0, losses: 4, pdiff: -26, seed: 0, name: "Kas" },
  },
  eventName: "Kings Cup 2023",
  eventLocation: "230 Kings Ct La Grange Park, IL 60???",
  teams: {
    round1: [
      ["p02", "p25"],
      ["p32", "p22"],
      ["p33", "p03"],
      ["p07", "p09"],
    ],
    round2: [
      ["p02", "p23"],
      ["p32", "p21"],
      ["p31", "p03"],
      ["p25", "p04"],
    ],
    round3: [
      ["p02", "p25"],
      ["p32", "p22"],
      ["p30", "p03"],
      ["p04", "p07"],
    ],
    round4: [
      ["p01", "p07"],
      ["p02", "p03"],
      ["p04", "p05"],
      ["p06", "p08"],
    ],
    finals: [
      ["p12", "p33"],
      ["p04", "p07"],
    ],
  },
  matches: [
    {
      id: "abc123",
      bracketName: "Prelims",
      bracketRound: "1",
      matchNumber: "1",
      maxScore: 11,
      winByTwo: false,
      startTime: null,
      endTime: null,
      winner: null,
      locationName: "Court 2",
      matchStatus: "",
      team1Ids: ["p01", "p32"],
      team1Name: "Rollerz",
      team1Score: 11,
      team2Ids: ["p01, p32"],
      team2Name: "Rollerz",
      team2Score: 6,
    },
  ],

  Locations: ["Court 1", "Court 2", "Court 3", "Court 4", "Court 5", "Court 6"],
};

export default initialdata;
